name = "password"
compatibility_date = "2024-05-01"

# This section configures your D1 Database.
[[d1_databases]]
binding = "DB"
database_name = "password"
database_id = "523df01e-9a94-4972-bea8-7b12968f5395"

# Functions directory
functions_dir = "functions"

# Pages configuration
[pages]
main_branch = "main"

[build.upload]
main = "functions/api/[[path]].ts"
