name = "password"
compatibility_date = "2024-05-01"

# This section configures your D1 Database.
[[d1_databases]]
# A binding name you can use in your code to reference the DB.
binding = "DB"
# The name of your database.
database_name = "password"
# The unique ID of your database.
database_id = "523df01e-9a94-4972-bea8-7b12968f5395"
